import { Product } from './types.js';

export const initialProducts: Product[] = [
  {
    _id: 'prod-001',
    name: 'Nike Air Zoom Pegasus 40',
    price: 139.99,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    category: 'Sports',
    description: 'A springy ride for every run, the Pegasus return to help you accomplish your goals. Breathable engineered mesh upper with responsive Zoom Air cushioning.',
    stock: 25,
    rating: 4.8,
    featured: true,
  },
  {
    _id: 'prod-002',
    name: 'Wilson Evolution Basketball',
    price: 64.99,
    image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=600&h=600&fit=crop',
    category: 'Sports',
    description: 'The preferred game basketball in high schools across America. Evo microfiber composite provides maximum grip and soft touch control.',
    stock: 40,
    rating: 4.9,
    featured: true,
  },
  {
    _id: 'prod-003',
    name: 'Garmin Forerunner 265 GPS Smartwatch',
    price: 449.99,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&h=600&fit=crop',
    category: 'Electronics',
    description: 'Brilliant AMOLED touchscreen display with advanced training metrics, recovery insights, and multi-band GPS tracking.',
    stock: 15,
    rating: 4.7,
    featured: true,
  },
  {
    _id: 'prod-004',
    name: 'Under Armour Seamless Training Hoodie',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&h=600&fit=crop',
    category: 'Fashion',
    description: 'Engineered mesh ventilation placed where you need it most. 4-way stretch material moves better in every direction and wicks sweat fast.',
    stock: 30,
    rating: 4.6,
    featured: true,
  },
  {
    _id: 'prod-005',
    name: 'Babolat Pure Aero Tennis Racket',
    price: 259.00,
    image: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=600&h=600&fit=crop',
    category: 'Sports',
    description: 'Aerodynamic frame engineered for ultimate spin and power. Aeromodular technology and Cortex Pure Feel provide supreme ball feel.',
    stock: 18,
    rating: 4.9,
    featured: false,
  },
  {
    _id: 'prod-006',
    name: 'Theragun Prime Percussive Massage Gun',
    price: 299.00,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop',
    category: 'Electronics',
    description: 'Deep muscle treatment simplified. QuietForce Technology delivers renowned Theragun power without disruptive noise for rapid athletic recovery.',
    stock: 20,
    rating: 4.8,
    featured: false,
  },
  {
    _id: 'prod-007',
    name: 'Giro Synthe MIPS II Cycling Helmet',
    price: 189.50,
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&h=600&fit=crop',
    category: 'Sports',
    description: 'Featherweight road cycling helmet offering impressive cooling power, minimalist profile, and integrated MIPS rotational energy protection.',
    stock: 12,
    rating: 4.7,
    featured: false,
  },
  {
    _id: 'prod-008',
    name: 'Hydro Flask 32 oz Wide Mouth Bottle',
    price: 44.95,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
    category: 'Home & Living',
    description: 'TempShield double-wall vacuum insulation keeps beverages cold for up to 24 hours or piping hot up to 12 hours. Pro-grade stainless steel.',
    stock: 50,
    rating: 4.9,
    featured: false,
  },
];
